### ISSUE TITLE
Air block prevents middle click

### ISSUE THREAD

**Issue by SkyWors** [AmyMialeeMods/visiblebarriers#22]
Hey ! If I have an instance with VisibleBarriers and LiteMatica, when I use my middle click on a block, an air block is systematically pickup preventing any other block from being taken.
This bug was tested with VB enabled and disabled.
After testing, if i disable the "pickBlockFirst" from litematica's config, the bug doesn't happen anymore.

**Comment by KadTheHunter** [comment]
I have this issue as well.

@SkyWors I'm not seeing a pickBlockFirst option in my Litematica config, are you sure that's what it's called? I do have easyPlaceFirst, but that's already disabled.

**Comment by KadTheHunter** [comment]
> I was talking about the keybind of this name

Ahhh, ok. Thank you, I found and disabled it now. 

Unfortunately it seems another side effect of VisibleBarriers is breaking the easyPlace mode of Litematica, so I'll just have to disable VB for the time being.
Hopefully this gets fixed soon!

**Comment by Earthcomputer** [comment]
This is due to Litematica's [RayTraceUtils](https://github.com/maruohon/litematica/blob/c10083a9d4848de85b8c589d940d06e1484a1236/src/main/java/fi/dy/masa/litematica/util/RayTraceUtils.java) calling `BlockState.getOutlineShape` without the `ShapeContext` parameter, which defaults to `ShapeContext.absent()`. VisibleBarriers then [checks](https://github.com/AmyMialeeMods/visible-barriers/blob/c891c725438ac1aa80f4a1f5958bcf4ee745077a/src/main/java/xyz/amymialee/visiblebarriers/mixin/AirBlockMixin.java#L36) against `ShapeContext.absent()` and returns a full cube. This causes Litematica's raycast to hit the air block inside your face in the litematic mirror world, when raycasting for a pick block in the litematic. Because this counts as a "successful" raycast, it then cancels vanilla's pick block because it thinks a pick block has been successful from the litematic mirror world. To fix this, Litematica needs to use an `EntityShapeContext` instead of `ShapeContext.absent()`, and I've verified this fixes the issue.

**Comment by Earthcomputer** [comment]
This was fixed in litematica 0.15.3
